server:
  port: 8088
spring:
  application:
    name: test-db2
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://43.228.77.178:50013/testdb:currentSchema=TEST;
    username: db2inst1
    password: ht_manager_0710
  jpa:
    database-platform: org.hibernate.dialect.DB2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


#mapper-locations应该具体查看target/classes下的目录结构
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/mapper/*Mapping.xml
  type-aliases-package: com.mvc.kgdemo.domain

#showSql
logging:
  level:
    com.mvc.kgdemo.mapper: debug
